# How to use multiZ

In [1]:
%reset -f

In [2]:
import sys
sys.path.append('../')

In [3]:
from multiZ.mcomplex import *

## 7. Arrays of multicomplex numbers

### 7.1. Creation

Similarly to the creation of a multicomplex number, it is possible to create an array of multicomplex numbers directly from its coefficient values.

Let's create a vector **u** and a matrix **M** made of multicomplex numbers.

In [4]:
u = marray([[  1,  2,  3],   # For vectors, use a 2D numpy array, or
            [  4,  5,  6],   # an equivalent nested list structure.
            [  7,  8,  9],
            [ 10, 11, 12],
            [ 13, 14, 15]])

In [5]:
M = marray([[[1,2],[3,4]],   # For 2D matrices, use a 3D array, or 
            [[5,6],[7,8]]])  # an equivalent nested list structure.

This example used the constructor of the mcomplex array class. If you call **u** or **M** you will get something similar to above inputs.

In [6]:
u                           # You can verify the contents of "u" this way.

marray([[ 1., 2., 3., 0.],
        [ 4., 5., 6., 0.],
        [ 7., 8., 9., 0.],
        [10.,11.,12., 0.],
        [13.,14.,15., 0.]])

In [7]:
M

marray([[[1.,2.],  [3.,4.]],
 [[5.,6.],  [7.,8.]]])

Each position in **u** and **M** is a multicomplex number.

In [8]:
u[0]

mcomplex([1.,2.,3.,0.])

In [9]:
u[1]

mcomplex([4.,5.,6.,0.])

In [10]:
M[0,0]

mcomplex([1.,2.])

And slices are arrays of multicomplex numbers

In [11]:
M[:,0]

marray([[1.,2.],
        [5.,6.]])

In [12]:
type(M[:,0])

multiZ.mcomplex.marray

All the multicomplex numbers stored in **u** share the same order and number of coefficients. Same applies for **M**.

In [13]:
u.order

2

In [14]:
u.numcoeffs

4

In [15]:
M.order

1

In [16]:
M.numcoeffs

2

Furthermore, **u** and **M** have shape and size, like a numpy arrays.

In [17]:
u.shape

(5,)

In [18]:
u.size

5

In [19]:
M.shape

(2, 2)

In [20]:
M.size

4

As you can notice, for the creation of any n-dimensional array of multicomplex you would need to input an array of dimensions n+1 of real numbers. However, this method is not particulary practical to convert a simple array of real numbers to multicomplex. Instead, you can use the function **`rarray`**.

In [21]:
u = rarray([1,2,3,4])

In [22]:
u

marray([[1.],
        [2.],
        [3.],
        [4.]])

In [23]:
M = rarray([[1, 2],
            [3, 4]])

In [24]:
M

marray([[[1.],  [2.]],
 [[3.],  [4.]]])

Another way of creating a multicomplex array is to use the function **zeros**.

In [25]:
v = zeros(4)

In [26]:
v

marray([[0.],
        [0.],
        [0.],
        [0.]])

In [27]:
P = zeros((2,2))

In [28]:
P

marray([[[0.],  [0.]],
 [[0.],  [0.]]])

It creates a vector of order 0 by default (real numbers). However, the desired order can be also given as an optional argument.

In [29]:
v = zeros(4, order=1)

In [30]:
v

marray([[0.,0.],
        [0.,0.],
        [0.,0.],
        [0.,0.]])

In [31]:
P = zeros((2,2), order=1)

In [32]:
P

marray([[[0.,0.],  [0.,0.]],
 [[0.,0.],  [0.,0.]]])

This is the most practical way for real work. Now, you can assign values to each vector position.

In [33]:
v[0] = 1.3                # You can assign real values,
v[1] = mcomplex([2, 3])   # or multicomplex numbers.
v[2] = 4 + 5*im(1) 

In [34]:
v[3,0] = 6              # You can also assign values
v[3,1] = 7              # to each mcx coefficient.

In [35]:
v

marray([[1.3,0. ],
        [2. ,3. ],
        [4. ,5. ],
        [6. ,7. ]])

In [36]:
P[0,0] = 1 + 2*im(1)
P[0,1] = 3

In [37]:
P[1,0,0] = 4
P[1,1,1] = 5

In [38]:
P

marray([[[1.,2.],  [3.,0.]],
 [[4.,0.],  [0.,5.]]])

### 7.2 About aliases and copies

Array objects are containers, and as such, they are affected by copy rules.

In [39]:
u = marray([[1,2],
            [3,4],
            [5,6]])

In [40]:
v = u           # This is a view, or an alias of u.
w = u.copy()    # And this is a copy.

In [41]:
v[0] = 100      # Changes in v will affect u.
w[0] = 200      # But changes in w will not affect u.

In [42]:
u

marray([[100.,  0.],
        [  3.,  4.],
        [  5.,  6.]])

In [43]:
v

marray([[100.,  0.],
        [  3.,  4.],
        [  5.,  6.]])

In [44]:
w

marray([[200.,  0.],
        [  3.,  4.],
        [  5.,  6.]])

### 7.3 Getting values of certain imaginary coefficient

The classes mcxvec and mcxmat provide two methods to extract values of an array that match an specified coefficient position or imaginary direction: **getCoef** and **imag**. The result of calling this method is a numpy array.

In [45]:
u = marray([[ 1,  2,  3,  4],
            [ 5,  6,  7,  8],
            [ 9, 10, 11, 12]])

Extracting only the multicomplex coefficient number 3, which also corresponds to the imaginary direction $i_1 i_2$.

In [46]:
u.getCoef(3)

array([ 4.,  8., 12.])

In [47]:
u.imag([1,2])

array([ 4.,  8., 12.])

### 7.4 Cauchy Riemann form of arrays 

To convert an array to its Cauchy Riemann form, use the **to_cr** method.

In [48]:
M = marray([[[1,2],[3,4]],
            [[5,6],[7,8]]])

In [49]:
u = marray([[1,2],
            [3,4]])

In [50]:
M_full = M.to_cr()

In [51]:
M_full

array([[ 1.,  3., -2., -4.],
       [ 5.,  7., -6., -8.],
       [ 2.,  4.,  1.,  3.],
       [ 6.,  8.,  5.,  7.]])

In [52]:
u_full = u.to_cr()

In [53]:
u_full

array([1., 3., 2., 4.])

You can also convert from Cauchy Riemann expanded version to multicomplex arrays using the **mcr_to_marray** function.

In [54]:
mcr_to_marray(M_full, order=1)

marray([[[1.,2.],  [3.,4.]],
 [[5.,6.],  [7.,8.]]])

In [55]:
mcr_to_marray(u_full, order=1)

marray([[1.,2.],
        [3.,4.]])